package com.offlineyoutube.offlineyoutube

import android.content.Context
import android.webkit.CookieManager
import android.util.Log
import java.io.File
import java.io.BufferedWriter
import java.io.OutputStreamWriter

/**
 * yt-dlp'ye verilecek Netscape biçimli çerez dosyasını üretir.
 *
 * Dosya ZORUNLU olarak düz metindir: yt-dlp `--cookies` seçeneğiyle dosyayı kendisi
 * okur, yani şifreli bir kap kullanılamaz. Bu yüzden önceki sürümdeki
 * `androidx.security.crypto.EncryptedFile` ve `MasterKey` import'ları hiçbir zaman
 * kullanılmıyordu ve yanlış bir güvenlik hissi veriyordu; ikisi de kaldırıldı.
 *
 * Bunun yerine gerçek koruma iki şeye dayanır:
 *  1. Dosya uygulamaya özel [Context.getCacheDir] altında tutulur (0700) ve manifest'te
 *     `allowBackup="false"` olduğu için yedeğe girmez.
 *  2. Ömrü mümkün olan en kısa süreye indirilir: çağıran taraf indirme bitince
 *     `finally` içinde siler, ayrıca [clearStaleCookieFiles] süreç öldürüldüğünde
 *     geride kalan artıkları bir sonraki kullanımda temizler.
 */
object CookieHelper {
    private const val TAG = "CookieHelper"
    private const val COOKIE_FILE_NAME = "youtube_cookies.txt"
    private const val TEMP_PREFIX = "youtube_cookies_tmp_"

    fun saveCookies(context: Context): File? {
        try {
            // Önceki koşulardan (süreç öldürülmesi, çökme) kalan artıklar temizlenir.
            clearStaleCookieFiles(context)

            val cookieManager = CookieManager.getInstance()
            val youtubeCookies = cookieManager.getCookie("https://youtube.com") ?: ""
            val googleCookies = cookieManager.getCookie("https://google.com") ?: ""

            if (youtubeCookies.isEmpty() && googleCookies.isEmpty()) return null

            val tempFile = File(context.cacheDir, "$TEMP_PREFIX${System.currentTimeMillis()}.txt")
            val finalFile = File(context.cacheDir, COOKIE_FILE_NAME)

            BufferedWriter(OutputStreamWriter(tempFile.outputStream(), Charsets.UTF_8)).use { writer ->
                writer.write("# Netscape HTTP Cookie File\n")
                writer.write("# This file is generated by Offline YouTube.\n\n")

                fun writeCookiesForDomain(cookieStr: String, domain: String) {
                    if (cookieStr.isEmpty()) return
                    val pairs = cookieStr.split(";")
                    for (pair in pairs) {
                        val parts = pair.trim().split("=", limit = 2)
                        if (parts.size == 2) {
                            val name = parts[0]
                            val value = parts[1]
                            val flag = "TRUE"
                            val path = "/"
                            val secure = "TRUE"
                            val expiration = "2147483647"

                            writer.write("$domain\t$flag\t$path\t$secure\t$expiration\t$name\t$value\n")
                        }
                    }
                }

                writeCookiesForDomain(youtubeCookies, ".youtube.com")
                writeCookiesForDomain(googleCookies, ".google.com")
            }
            cookieManager.flush()

            // Atomik takas. renameTo başarısız olabilir; dönüş değeri kontrol edilmezse
            // geçici dosya oturum çerezleriyle birlikte cacheDir'de kalıcı olarak birikir.
            if (finalFile.exists() && !finalFile.delete()) {
                Log.w(TAG, "Eski çerez dosyası silinemedi, geçici dosya temizleniyor")
                tempFile.delete()
                return null
            }
            if (!tempFile.renameTo(finalFile)) {
                Log.w(TAG, "Çerez dosyası taşınamadı, geçici dosya temizleniyor")
                tempFile.delete()
                return null
            }

            Log.d(TAG, "Çerez dosyası yazıldı (düz metin, yt-dlp gereği); kullanım sonrası silinir")
            return finalFile
        } catch (e: Exception) {
            Log.e(TAG, "Error saving cookies", e)
            return null
        }
    }

    /**
     * Önceki koşulardan kalan çerez dosyalarını siler.
     *
     * Normal akışta çağıran taraf dosyayı `finally` içinde siler, ama uygulama süreci
     * öldürülürse o blok hiç çalışmaz ve tam Google oturum çerezleri diskte kalır.
     */
    fun clearStaleCookieFiles(context: Context) {
        try {
            context.cacheDir.listFiles()?.forEach { f ->
                if (f.isFile && (f.name == COOKIE_FILE_NAME || f.name.startsWith(TEMP_PREFIX))) {
                    f.delete()
                }
            }
        } catch (e: Exception) {
            Log.w(TAG, "Artık çerez dosyaları temizlenemedi: ${e.message}")
        }
    }
}
