package com.offlineyoutube.offlineyoutube

import android.content.Context
import android.webkit.CookieManager
import android.util.Log
import androidx.security.crypto.EncryptedFile
import androidx.security.crypto.MasterKey
import java.io.File
import java.io.BufferedWriter
import java.io.OutputStreamWriter

object CookieHelper {
    private const val TAG = "CookieHelper"

    fun saveCookies(context: Context): File? {
        try {
            val cookieManager = CookieManager.getInstance()
            val youtubeCookies = cookieManager.getCookie("https://youtube.com") ?: ""
            val googleCookies = cookieManager.getCookie("https://google.com") ?: ""
            
            if (youtubeCookies.isEmpty() && googleCookies.isEmpty()) return null

            val tempFile = File(context.cacheDir, "youtube_cookies_tmp_${System.currentTimeMillis()}.txt")
            val finalFile = File(context.cacheDir, "youtube_cookies.txt")

            BufferedWriter(OutputStreamWriter(tempFile.outputStream(), Charsets.UTF_8)).use { writer ->
                writer.write("# Netscape HTTP Cookie File\n")
                writer.write("# This file is generated by Offline YouTube.\n\n")

                fun writeCookiesForDomain(cookieStr: String, domain: String) {
                    if (cookieStr.isEmpty()) return
                    val pairs = cookieStr.split(";")
                    for (pair in pairs) {
                        val parts = pair.trim().split("=", limit = 2)
                        if (parts.size == 2) {
                            val name = parts[0]
                            val value = parts[1]
                            val flag = "TRUE"
                            val path = "/"
                            val secure = "TRUE"
                            val expiration = "2147483647"

                            writer.write("$domain\t$flag\t$path\t$secure\t$expiration\t$name\t$value\n")
                        }
                    }
                }

                writeCookiesForDomain(youtubeCookies, ".youtube.com")
                writeCookiesForDomain(googleCookies, ".google.com")
            }
            cookieManager.flush()
            
            // Atomic swap
            if (finalFile.exists()) {
                finalFile.delete()
            }
            tempFile.renameTo(finalFile)
            
            Log.d(TAG, "Cookies securely saved as plain text for yt-dlp")
            return finalFile
        } catch (e: Exception) {
            Log.e(TAG, "Error saving cookies", e)
            return null
        }
    }
}
