package com.offlineyoutube.offlineyoutube

import android.content.Context
import android.webkit.CookieManager
import android.util.Log
import java.io.File

object CookieHelper {
    private const val TAG = "CookieHelper"

    fun saveCookies(context: Context): File? {
        try {
            val cookieManager = CookieManager.getInstance()
            val cookieStr = cookieManager.getCookie("https://youtube.com") ?: return null
            if (cookieStr.isEmpty()) return null

            val cookiesFile = File(context.cacheDir, "youtube_cookies.txt")
            cookiesFile.bufferedWriter().use { writer ->
                writer.write("# Netscape HTTP Cookie File\n")
                writer.write("# This file is generated by Offline YouTube.\n\n")

                val pairs = cookieStr.split(";")
                for (pair in pairs) {
                    val parts = pair.trim().split("=", limit = 2)
                    if (parts.size == 2) {
                        val name = parts[0]
                        val value = parts[1]
                        // domain, flag, path, secure, expiration, name, value
                        val domain = ".youtube.com"
                        val flag = "TRUE"
                        val path = "/"
                        val secure = "TRUE"
                        // 2147483647 is year 2038
                        val expiration = "2147483647"

                        writer.write("$domain\t$flag\t$path\t$secure\t$expiration\t$name\t$value\n")
                    }
                }
            }
            cookieManager.flush()
            Log.d(TAG, "Cookies saved to ${cookiesFile.absolutePath}")
            return cookiesFile
        } catch (e: Exception) {
            Log.e(TAG, "Error saving cookies", e)
            return null
        }
    }
}
