name: Flutter CI/CD & Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.x' # Projenin kullandığı sürüm aralığı
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Run Flutter Analyze
      run: flutter analyze

    - name: Run Flutter Tests
      run: flutter test

    - name: Build Release APK
      run: flutter build apk --release

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
